# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

#logging:
#  level:
#  ROOT: DEBUG
#  io.bird: DEBUG

spring:
  profiles:
    active: dev
    include: swagger

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jackson:
    serialization.indent_output: true

  flyway:
    enabled: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basket_io?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: eternal

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    #properties:
    #  hibernate.id.new_generator_mappings: true
    #  hibernate.cache.use_second_level_cache: true
    #  hibernate.cache.use_query_cache: false
    #  hibernate.generate_statistics: true
    #  hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
    #  hibernate.cache.hazelcast.instance_name: test
    #  hibernate.cache.use_minimal_puts: true
    #  hibernate.cache.hazelcast.use_lite_member: true
  #mail:
  #  host: localhost
  #  port: 25
  #  username:
  #  password:

  messages:
    cache-seconds: 1

api:
  security:
    username: 1
    password: 1

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias test -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" config looks like:
#
# server:
#  port: 8443
#  ssl:
#    key-store: keystore.p12
#    key-store-password: <your-password>
#    key-store-type: PKCS12
#    key-alias: test
# ===================================================================
server:
  port: 8080

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe config, like in the JHipsterProperties above
#
# More documentation is available at:
# http://www.jhipster.tech/common-application-properties/
# ===================================================================


